const ADD_TASK = 'ADD_TASK';
const EDIT_STATUS = 'EDIT_STATUS';
const REMOVE_TASK = 'REMOVE_TASK';
const OPEN_DRAWER = 'OPEN_DRAWER';
const HANDLE_FORM_FIELDS = 'HANDLE_FORM_FIELDS';
const HANDLE_FORM_IS_EDIT = 'HANDLE_FORM_IS_EDIT';
const HANDLE_FORM_EDIT = 'HANDLE_FORM_EDIT';
const HIDE_FIELDS = 'HIDE_FIELDS';

export {
  ADD_TASK,
  EDIT_STATUS,
  REMOVE_TASK,
  OPEN_DRAWER,
  HANDLE_FORM_FIELDS,
  HANDLE_FORM_IS_EDIT,
  HANDLE_FORM_EDIT,
  HIDE_FIELDS
};
